### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kotovasia5120** [clinlx/CN_GreenLumaGUI#34]
if the game has unlocked dlc via creamAPI and starts scanning for available dlc, it crashes.

**Comment by clinlx** [comment]
Could you clarify which process is crashing? Is it the Steam process or the tool itself? 
Also, would it be possible for you to provide detailed steps to reproduce the issue?

**Comment by kotovasia5120** [comment]
Creamapi is used in Forza horizon 5. 
In the tool, I click to get a list of add-ons. 
The tool overestimates the work without notifications.

**Comment by clinlx** [comment]
This may not be a technical bug. In my tool, the "retrieve available DLCs for a game" feature is not actually connected to the Steam client, nor can it conflict with CreamAPI. What the tool does is simply access Steam's official website through a browser and download the data from there.

The issue you encountered is likely caused by other software interfering with your network connection or slowing down your internet speed. For instance, some programs might block access to Steam’s website to prevent updates or to bypass DLC ownership verification.

This particular game has a lot of DLCs—52 in total. If the internet connection is slow, even at just 2 seconds per DLC, it would take 104 seconds to complete the process. In theory, the tool should not have frozen; it should notify you of success or failure after a long wait.

However, the lack of detailed notifications or a progress bar is indeed a design oversight on my part.

**Comment by clinlx** [comment]
The tool will wait up to 15 seconds for each DLC. If the network request fails for every DLC, it could take as long as 15 * 52 = 780 seconds before the tool provides the next update—and even then, the DLCs won't be successfully added to the list. I only tested it under good network conditions and didn't consider how long it would take without any notifications if the network fails.

**Comment by kotovasia5120** [comment]
The manager simply closes without notification. On other applications, everything happened quickly. But there certainly isn't much dlc. On the flyleaf, the program closes itself.

**Comment by clinlx** [comment]
OK, I will check it, but for now, I can't fix it because I'm unable to reproduce the crash in my environment.
What I don't understand is why the tool itself is crashing—it shouldn't have anything to do with CreamAPI. If it were Steam or the game crashing, that would be more plausible. However, if Steam or the game is crashing, there's nothing I can do to resolve that.
